version: "3"

services: 

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "$PWD/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/docker/nginx/log/:/var/log/nginx"
      - "$PWD/docker/nginx/conf/conf.d:/etc/nginx/conf.d"
      - "/www/jaysun/php/:/usr/share/nginx/html"
    networks:
      default:
        ipv4_address: 172.18.0.2

  mysql:
    image: "mysql:5.7.25"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - $PWD/docker/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.18.0.6

# networks:
#   app_net:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.18.1.0/16