version: "3"

services: 
  
  mysql:
    image: "mysql:5.7.25"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - $PWD/docker/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.19.0.6

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/16